# <div style="text-align: right"> Example Use. </div>

---

<div style="text-align: right"> Geoff Counihan - Oct 7, 2017 </div>

In [15]:
import pandas as pd
import numpy as np

In [16]:
from scratch import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [3]:
Xy = pd.read_csv('./sonar.all-data.csv',header=None)
Xy[60] = Xy[60].map({'R':0,'M':1})
X = np.array(Xy.iloc[:,:-1])
y = np.array(Xy.iloc[:,-1])
Xy = np.array(Xy)

# Decision Tree

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=35)

In [5]:
rf = random_forest(max_depth=2,num_trees=3,min_num_split=30)
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)

In [6]:
confusion_matrix(rf_pred,y_test)

array([[18,  6],
       [12, 16]])

In [7]:
accuracy(rf_pred,y_test)

0.6538461538461539

# Random Forest

In [9]:
dt = decision_tree(max_depth=3,min_num_split=30)
dt.fit(X_train,y_train)
dt_pred = dt.predict(X_test)

In [10]:
confusion_matrix(dt_pred,y_test)

array([[18,  6],
       [12, 16]])

In [11]:
accuracy(dt_pred,y_test)

0.6538461538461539

# KNN

In [12]:
knn = k_nearest_neighbors()
knn.fit(X_train,y_train)
knn_pred = knn.predict(X_test)

0 ties


In [13]:
confusion_matrix(knn_pred,y_test)

array([[28,  8],
       [ 2, 14]])

In [14]:
accuracy(knn_pred,y_test)

0.8076923076923077